### ISSUE TITLE
FunctionClauseError in Peel.scan function

### ISSUE THREAD

**Issue by banjophil** [strobe-audio/strobe-hub#47]
In OSX 10.12.6

** (FunctionClauseError) no function clause matching in System.cmd/3    
    
    The following arguments were given to System.cmd/3:
    
        # 1
        nil
    
        # 2
        ["-show_format", "-show_streams", "-print_format", "json", "-v", "quiet", "/Users/philipdaniel/Documents/GitHub/strobe-hub/Music/Users/philipdaniel/Documents/GitHub/strobe-hub/Music/Heath Cullen/Outsiders/Heath Cullen - outsiders - 01 Another Blue World.mp3"]
    
        # 3
        []
    
    Attempted function clauses (showing 1 out of 1):
    
        def cmd(command, args, opts) when is_binary(command) and is_list(args)
    
    (elixir) lib/system.ex:619: System.cmd/3
    (peel) lib/peel/metadata/ffprobe.ex:44: Peel.Importer.Ffprobe.read_metadata/1
    (peel) lib/peel/metadata/ffprobe.ex:14: Peel.Importer.Ffprobe.read/1
    (peel) lib/peel/importer.ex:23: Peel.Importer.create_track/2
    (peel) lib/peel/scanner.ex:20: Peel.Scanner.scan/2
    (elixir) lib/enum.ex:771: anonymous fn/3 in Enum.each/2
    (elixir) lib/enum.ex:2979: anonymous fn/3 in Enum.each/2
    (elixir) lib/stream.ex:1541: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/stream.ex:1379: Stream.do_resource/5
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:2979: Enum.each/2
    (peel) lib/peel/scanner.ex:8: Peel.Scanner.start/1
    (peel) lib/peel.ex:44: Peel.scan/1
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/code.ex:232: Code.eval_string/3
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/tasks/run.ex:142: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1

**Comment by banjophil** [comment]
Error was caused as ffmpeg was missing on my system. Installed with brew.
